title: Etini Akpayang # your name (or website title) here
logo: "/images/Screenshot_20230329_004834.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>
Welcome to my portfolio! I am a statistics graduate with a Bachelor's degree from University of Uyo and a Masters degree in statistics from Ahmadu Bello University Zaria. My primary interests lie in Bayesian statistics and machine learning, where I have honed my skills in utilizing these methodologies to solve complex statistical problems.

Throughout my academic journey, I have conducted extensive research on the impact of covariance structures on estimates, which has contributed significantly to the advancement of statistical models and methodologies. I am proficient in statistical software tools such as R, SAS, and Python, and possess the ability to apply statistical theories and techniques to real-world problems.

This portfolio showcases my expertise in statistical methodologies and techniques, and demonstrates my ability to apply statistical techniques to solve complex problems in innovative ways. I am passionate about finding innovative solutions to statistical challenges and am committed to leveraging my expertise to provide impactful solutions to organizations and teams working in the field of statistical analysis.

Thank you for visiting my portfolio, and I look forward to connecting with you to discuss how my skills and expertise can contribute to the success of your organization or project.<br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/etini-akpayang-754aa4101">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
