# _config.yml

title: ETINI AKPAYANG
logo: "/images/Screenshot_20230329_004834.jpg?raw=true"
description: > 
  Welcome to my GitHub portfolio! As a highly skilled statistician with a Bachelor's degree in Statistics from the University of Uyo and a Master's degree in Statistics from Ahmadu Bello University, I bring a wealth of knowledge and expertise to the world of data analysis. With a passion for unraveling the stories hidden within data, I have dedicated my career to mastering statistical methodologies and cutting-edge tools. Proficient in packages like R, SPSS, and Excel, I have honed my skills in data manipulation, visualization, and advanced statistical analysis. I believe in the power of data-driven insights to drive informed decision-making and foster growth.


   - [View my LinkedIn Profile](https://www.linkedin.com/in/etini-akpayang-754aa4101)
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0

colors:
  crimson: '#900C3F'
