title: Etini Akpayang

logo: "/images/Screenshot_20230329_004834.jpg?raw=true"

description: |

  Welcome to my portfolio! I am a statistics graduate with a Bachelor's degree from the University of Uyo and a Master's degree in statistics from Ahmadu Bello University Zaria. My primary interests lie in Bayesian statistics and machine learning, where I have honed my skills in utilizing these methodologies to solve complex statistical problems.

  Throughout my academic journey, I have conducted extensive research on the impact of covariance structures on estimates, which has contributed significantly to the advancement of statistical models and methodologies. I am proficient in statistical software tools such as R, SAS, and Python, and possess the ability to apply statistical theories and techniques to real-world problems.

  <br>
# add a new section for links to your social media and professional profiles

# you can add more links if you have them

links:

  LinkedIn: https://www.linkedin.com/in/etini-akpayang-754aa4101/

# add text justification for the main description

defaults:

  - scope:

      path: ""

      type: "posts"

    values:

      layout: "post"

      text_justify: "true"

remote_theme: pages-themes/minimal@v0.2.0

plugins:

  - jekyll-remote-theme

  - jekyll-text-justify # add this plugin for text justification

google_analytics: UA-000000-0 # your Google Analytics tracking ID here

