# _config.yml

name: Your Name
title: Data Analyst | Statistician
email: your@email.com
description: Passionate about extracting insights from data and driving data-informed decision-making.

# Social media links
social:
  - title: LinkedIn
    url: https://www.linkedin.com/in/your-linkedin-profile
  - title: GitHub
    url: https://github.com/your-github-profile
  - title: Twitter
    url: https://twitter.com/your-twitter-profile

# Skills
skills:
  - title: Statistical Analysis
  - title: Data Visualization
  - title: Machine Learning
  - title: R Programming
  - title: SPSS
  - title: Excel

# Education
education:
  - degree: Bachelor of Science in Statistics
    university: University of Uyo
    year: 20XX
  - degree: Master of Science in Statistics
    university: Ahmadu Bello University
    year: 20XX

# Projects
projects:
  - title: Market Research Analysis
    description: Conducted a comprehensive market research analysis for a leading company, providing insights into consumer behavior and market trends.
    github: https://github.com/your-github-profile/market-research-analysis

  - title: Predictive Modeling
    description: Developed a predictive model using machine learning algorithms to forecast customer churn in the telecommunications industry.
    github: https://github.com/your-github-profile/predictive-modeling

  # Add more projects as desired

# Footer text
footer_text: "© 2023 Etini Akpayang. All rights reserved."
